apps/blog/urls.py
from django.urls import path
from .views import(
    lista_blog_crud,
    registrar_blog,
    eliminar_blog,
    edicionBlog,
    editar_blog
)

app_name = 'blog'

urlpatterns = [
    path('', lista_blog_crud, name='home'),
    path('registrar/', registrar_blog, name='registrar'),
    path('eliminar/<codigo>', eliminar_blog, name='eliminar'),
    path('edicion/<codigo>', edicionBlog, name='edicion'),
    path('editar/', editar_blog, name='editar'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.blog.urls', namespace='blog')),
]

apps/blog/models.py
from django.db import models


# Create your models here.

## CRUD

class blog_crud(models.Model):
    codigo = models.CharField(primary_key=True, max_length=6)
    nombre = models.CharField(max_length=50)
    creditos = models.PositiveSmallIntegerField()

    def __str__(self):
        texto = "{0} ({1})"
        return texto.format(self.nombre, self.creditos)

apps/login/models.py
from django.db import models

# Create your models here.

apps/blog/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import blog_crud

# Create your views here.

template_name = "blog/index.html"

def lista_blog_crud(request):
    objetos = blog_crud.objects.all()
    return render(request, template_name, {'objetos': objetos})



def registrar_blog(request):
    codigo = request.POST['txtCodigo']
    nombre = request.POST['txtNombre']
    creditos = request.POST['numCreditos']

    curso = blog_crud.objects.create(
        codigo=codigo, nombre=nombre, creditos=creditos)
    messages.success(request, 'BLOG registrado!')
    return redirect('/')



def eliminar_blog(request, codigo):

    curso = blog_crud.objects.get(codigo=codigo)
    curso.delete()

    messages.success(request, 'BLOG elimnado!')
    return redirect('/')





def edicionBlog(request, codigo):
    objeto = blog_crud.objects.get(codigo=codigo)
    return render(request, "blog/edition.html", {'objeto': objeto})


def editar_blog(request):
    codigo = request.POST['txtCodigo']
    nombre = request.POST['txtNombre']
    creditos = request.POST['numCreditos']

    curso = blog_crud.objects.get(codigo=codigo)
    curso.nombre = nombre
    curso.creditos = creditos
    curso.save()


    messages.success(request, 'BLOG editado!')
    return redirect('/')

apps/login/views.py
from django.shortcuts import render

# Create your views here.

templates/blog/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-info">
        <a class="navbar-brand" href="#">Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contacto</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container py-4">
        {% block body %}

        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous">
    </script>

</body>

</html>

templates/blog/edition.html
{% extends "./base.html" %}

{% block title %} Edicion Blog {% endblock %}

{% block body %}
<div class="row">
    <div class="col-md-4 offset-md-4">
        <h2>Edición de Curso</h2>
        <div class="card">
            <div class="card-body">
                <form action="{%  url 'blog:editar' %}" method="POST">{% csrf_token %}
                    <div class="form-group">
                        <input type="text" id="txtCodigo" name="txtCodigo" value="{{objeto.codigo}}" class="form-control" placeholder="Código"
                            minlength="6" maxlength="6" readonly required>
                    </div>
                    <div class="form-group">
                        <input type="text" id="txtNombre" name="txtNombre" value="{{objeto.nombre}}" class="form-control" placeholder="Nombre"
                            maxlength="50" required>
                    </div>
                    <div class="form-group">
                        <input type="text" id="numCreditos" name="numCreditos" value="{{objeto.creditos}}" class="form-control" min="1" max="9"
                            value="1" required>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success btn-block text-white">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/blog/index.html
{% extends "./base.html" %} 

{% block title %} Blog Principal{% endblock %} 

{%block body %}

<div class="row">
  <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
    {% if messages %} {% for message in messages %}
    <div class="alert alert-dismissible alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong class="text-dark">{{ message }}</strong>
    </div>
    {% endfor %} {% endif %}
    <h2>CRUD Blog</h2>
    <div class="card">
      <div class="card-body">
        <form action="{%  url 'blog:registrar' %}" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <input
              type="text"
              id="txtCodigo"
              name="txtCodigo"
              class="form-control"
              placeholder="Código"
              minlength="6"
              maxlength="6"
              required
            />
          </div>
          <div class="form-group">
            <input
              type="text"
              id="txtNombre"
              name="txtNombre"
              class="form-control"
              placeholder="Nombre"
              maxlength="50"
              required
            />
          </div>
          <div class="form-group">
            <input
              type="text"
              id="numCreditos"
              name="numCreditos"
              class="form-control"
              min="1"
              max="9"
              value="1"
              required
            />
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-success btn-block text-white">
              Guardar
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <div class="col-sm-12 col-md-6 col-lg-8 col-xl-8">
    <h1>Lista de objetos Blog CRUD</h1>
    <table>
      <thead>
        <tr>
          <th>Código</th>
          <th>Nombre</th>
          <th>Créditos</th>
        </tr>
      </thead>
      <tbody>
        {% for objeto in objetos %}
        <tr>
          <td>{{ objeto.codigo }}</td>
          <td>{{ objeto.nombre }}</td>
          <td>{{ objeto.creditos }}</td>
          <td><a href="{% url 'blog:edicion' objeto.codigo %}" class="btn btn-info">Editar</a></td>
          <td><a href="{% url 'blog:eliminar' objeto.codigo %}" class="btn btn-danger btnEliminacion">Eliminar</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}